; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
  someweisguy/esp_dmx ;Manually fix line 32 in /src/dmx/hal/uart.c to #if SOC_UART_NUM > 2
  bblanchon/ArduinoJson@^6.21.5
  makuna/NeoPixelBus
  s00500/ESPUI
  adafruit/Adafruit SSD1306
board_build.filesystem = littlefs
;board_build.partitions = default_ota.csv
upload_speed = 921600
monitor_speed = 115200
build_flags =
  -Wno-macro-redefined
  -Wno-deprecated-declarations
;  -D DEBUG
;  -D DEBUG_ESPUI
  -D ESPUI_LITTLEFS
;  -D SOLE_OUTPUT
;  -D OLED
	-D FIRMARE_VER=0x0300 ;Firmware given over Artnet (2 bytes)
	-D CONFIG_ESP32_WIFI_RX_BUFFER_NUM=16
  -D CONFIG_ESP32_WIFI_TX_BUFFER_NUM=16
  -D CONFIG_LWIP_MAX_SOCKETS=16
  -D CONFIG_LWIP_SO_REUSE=1
  -D CONFIG_LWIP_TCP_QUEUE_OOSEQ=0
; build_type = debug

[env:esp-07]
platform = espressif8266
framework = arduino
board = esp07
lib_deps = 
  https://github.com/DJMaxergy/DmxRdmLib_esp8266.git#3300dbb
  bblanchon/ArduinoJson@^6.21.5
  makuna/NeoPixelBus
  s00500/ESPUI
  adafruit/Adafruit SSD1306
board_build.f_cpu = 160000000L
board_build.flash_mode = dout
board_build.filesystem = littlefs
board_build.lwip_variant = v2_high_bandwidth
board_upload.resetmethod = nodemcu
upload_speed = 921600
monitor_speed = 115200
build_flags =
  -Wno-deprecated-declarations
;  -D DEBUG
;  -D DEBUG_ESPUI
  -D ESPUI_LITTLEFS
;  -D SOLE_OUTPUT
;  -D OLED
	-D FIRMARE_VER=0x0300 ;Firmware given over Artnet (2 bytes)
  -D LWIP_FEATURES=1
  -D LWIP_IPV6=0
  -D TCP_MSS=1460
  -D TCP_SND_BUF=2920
  -D TCP_WND=2920
  -D TCP_SND_QUEUELEN=8
; build_type = debug
; monitor_filters = esp8266_exception_decoder

[env:d1_mini]
platform = espressif8266
framework = arduino
board = d1_mini
lib_deps = 
  https://github.com/DJMaxergy/DmxRdmLib_esp8266.git#3300dbb
  bblanchon/ArduinoJson@^6.21.5
  makuna/NeoPixelBus
  s00500/ESPUI
  adafruit/Adafruit SSD1306
board_build.f_cpu = 160000000L
board_build.filesystem = littlefs
board_build.lwip_variant = v2_high_bandwidth
upload_speed = 921600
monitor_speed = 115200
build_flags =
  -Wno-deprecated-declarations
;  -D DEBUG
;  -D DEBUG_ESPUI
  -D ESPUI_LITTLEFS
;  -D SOLE_OUTPUT
;  -D OLED
	-D FIRMARE_VER=0x0300 ;Firmware given over Artnet (2 bytes)
  -D LWIP_FEATURES=1
  -D LWIP_IPV6=0
  -D TCP_MSS=1460
  -D TCP_SND_BUF=2920
  -D TCP_WND=2920
  -D TCP_SND_QUEUELEN=8
; build_type = debug
; monitor_filters = esp8266_exception_decoder

[env:d1_mini_pro]
platform = espressif8266
framework = arduino
board = d1_mini_pro
lib_deps = 
  https://github.com/DJMaxergy/DmxRdmLib_esp8266.git#3300dbb
  bblanchon/ArduinoJson@^6.21.5
  makuna/NeoPixelBus
  s00500/ESPUI
  adafruit/Adafruit SSD1306
board_build.f_cpu = 160000000L
board_build.filesystem = littlefs
board_build.lwip_variant = v2_high_bandwidth
upload_speed = 921600
monitor_speed = 115200
build_flags =
  -Wno-deprecated-declarations
;  -D DEBUG
;  -D DEBUG_ESPUI
  -D ESPUI_LITTLEFS
;  -D SOLE_OUTPUT
;  -D OLED
	-D FIRMARE_VER=0x0300 ;Firmware given over Artnet (2 bytes)
  -D LWIP_FEATURES=1
  -D LWIP_IPV6=0
  -D TCP_MSS=1460
  -D TCP_SND_BUF=2920
  -D TCP_WND=2920
  -D TCP_SND_QUEUELEN=8
; build_type = debug
; monitor_filters = esp8266_exception_decoder
