; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp-07

[env:esp-07]
platform = espressif8266
framework = arduino
board = esp07
lib_deps = 
  https://github.com/DJMaxergy/DmxRdmLib_esp8266.git#a8f4f34
  bblanchon/ArduinoJson@^6.21.5
  makuna/NeoPixelBus
  s00500/ESPUI
  adafruit/Adafruit SSD1306
board_build.f_cpu = 160000000L
board_build.flash_mode = dout
board_build.filesystem = littlefs
board_build.lwip_variant = v2_high_bandwidth
board_upload.resetmethod = nodemcu
upload_speed = 921600
monitor_speed = 115200
; monitor_filters = esp8266_exception_decoder
; build_type = debug
build_flags =
  -Wno-deprecated-declarations
  -D LWIP_FEATURES=1
  -D LWIP_IPV6=0
  -D TCP_MSS=1460
  -D TCP_SND_BUF=2920
  -D TCP_WND=2920
  -D TCP_SND_QUEUELEN=8
;  -D DEBUG
;  -D DEBUG_ESPUI
  -D ESPUI_LITTLEFS
;  -D SOLE_OUTPUT
;  -D OLED
	-D FIRMARE_VER=0x0300   ; Firmware given over Artnet (2 bytes)
  -D PIN_DMX_DIR_A=13     ; D1 Mini: D7
  -D PIN_DMX_DIR_B=16     ; D1 Mini: D0
  -D PIN_PORT_A_TX=1      ; D1 Mini: TX
  -D PIN_PORT_B_TX=2      ; D1 Mini: D4
  -D PIN_PORT_A_RX=3      ; D1 Mini: RX
  -D PIN_PORT_B_RX=-1     ; just a dummy
  -D PIN_STATUS_LED=12    ; D1 Mini: D6
  -D PIN_RESET_CONFIG=14  ; D1 Mini: D5

[env:d1_mini]
platform = espressif8266
framework = arduino
board = d1_mini
lib_deps = 
  https://github.com/DJMaxergy/DmxRdmLib_esp8266.git#a8f4f34
  bblanchon/ArduinoJson@^6.21.5
  makuna/NeoPixelBus
  s00500/ESPUI
  adafruit/Adafruit SSD1306
board_build.f_cpu = 160000000L
board_build.filesystem = littlefs
board_build.lwip_variant = v2_high_bandwidth
upload_speed = 921600
monitor_speed = 115200
; monitor_filters = esp8266_exception_decoder
; build_type = debug
build_flags =
  -Wno-deprecated-declarations
  -D LWIP_FEATURES=1
  -D LWIP_IPV6=0
  -D TCP_MSS=1460
  -D TCP_SND_BUF=2920
  -D TCP_WND=2920
  -D TCP_SND_QUEUELEN=8
;  -D DEBUG
;  -D DEBUG_ESPUI
  -D ESPUI_LITTLEFS
;  -D SOLE_OUTPUT
;  -D OLED
	-D FIRMARE_VER=0x0300   ; Firmware given over Artnet (2 bytes)
  -D PIN_DMX_DIR_A=13     ; D1 Mini: D7
  -D PIN_DMX_DIR_B=16     ; D1 Mini: D0
  -D PIN_PORT_A_TX=1      ; D1 Mini: TX
  -D PIN_PORT_B_TX=2      ; D1 Mini: D4
  -D PIN_PORT_A_RX=3      ; D1 Mini: RX
  -D PIN_PORT_B_RX=-1     ; just a dummy
  -D PIN_STATUS_LED=12    ; D1 Mini: D6
  -D PIN_RESET_CONFIG=14  ; D1 Mini: D5

[env:d1_mini_pro]
platform = espressif8266
framework = arduino
board = d1_mini_pro
lib_deps = 
  https://github.com/DJMaxergy/DmxRdmLib_esp8266.git#a8f4f34
  bblanchon/ArduinoJson@^6.21.5
  makuna/NeoPixelBus
  s00500/ESPUI
  adafruit/Adafruit SSD1306
board_build.f_cpu = 160000000L
board_build.filesystem = littlefs
board_build.lwip_variant = v2_high_bandwidth
upload_speed = 921600
monitor_speed = 115200
; monitor_filters = esp8266_exception_decoder
; build_type = debug
build_flags =
  -Wno-deprecated-declarations
  -D LWIP_FEATURES=1
  -D LWIP_IPV6=0
  -D TCP_MSS=1460
  -D TCP_SND_BUF=2920
  -D TCP_WND=2920
  -D TCP_SND_QUEUELEN=8
;  -D DEBUG
;  -D DEBUG_ESPUI
  -D ESPUI_LITTLEFS
;  -D SOLE_OUTPUT
;  -D OLED
	-D FIRMARE_VER=0x0300   ; Firmware given over Artnet (2 bytes)
  -D PIN_DMX_DIR_A=13     ; D1 Mini: D7
  -D PIN_DMX_DIR_B=16     ; D1 Mini: D0
  -D PIN_PORT_A_TX=1      ; D1 Mini: TX
  -D PIN_PORT_B_TX=2      ; D1 Mini: D4
  -D PIN_PORT_A_RX=3      ; D1 Mini: RX
  -D PIN_PORT_B_RX=-1     ; just a dummy
  -D PIN_STATUS_LED=12    ; D1 Mini: D6
  -D PIN_RESET_CONFIG=14  ; D1 Mini: D5

[env:wemos_d1_mini32]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps =
  someweisguy/esp_dmx ;Manually fix line 32 in /src/dmx/hal/uart.c to #if SOC_UART_NUM > 2
  bblanchon/ArduinoJson@^6.21.5
  makuna/NeoPixelBus
  s00500/ESPUI
  adafruit/Adafruit SSD1306
board_build.filesystem = littlefs
upload_speed = 921600
monitor_speed = 115200
; monitor_filters = esp32_exception_decoder
; build_type = debug
build_flags =
  -Wno-deprecated-declarations
	-D CONFIG_ESP32_WIFI_RX_BUFFER_NUM=16
  -D CONFIG_ESP32_WIFI_TX_BUFFER_NUM=16
  -D CONFIG_LWIP_MAX_SOCKETS=16
  -D CONFIG_LWIP_SO_REUSE=1
  -D CONFIG_LWIP_TCP_QUEUE_OOSEQ=0
;  -D DEBUG
;  -D DEBUG_ESPUI
  -D ESPUI_LITTLEFS
;  -D SOLE_OUTPUT
;  -D OLED
	-D FIRMARE_VER=0x0300   ; Firmware given over Artnet (2 bytes)
  -D PIN_DMX_DIR_A=23     ; equals D1mini D7
  -D PIN_DMX_DIR_B=26     ; equals D1mini D0
  -D PIN_PORT_A_TX=1      ; equals D1mini TX
  -D PIN_PORT_B_TX=16     ; equals D1mini D4
  -D PIN_PORT_A_RX=3      ; equals D1mini RX
  -D PIN_PORT_B_RX=-1     ; just a dummy
  -D PIN_STATUS_LED=19    ; equals D1mini D6
  -D PIN_RESET_CONFIG=18  ; equals D1mini D5
  -D PIN_OLED_SDA=21      ; equals D1mini D2
  -D PIN_OLED_SCL=22      ; equals D1mini D1

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
  someweisguy/esp_dmx ;Manually fix line 32 in /src/dmx/hal/uart.c to #if SOC_UART_NUM > 2
  bblanchon/ArduinoJson@^6.21.5
  makuna/NeoPixelBus
  s00500/ESPUI
  adafruit/Adafruit SSD1306
board_build.filesystem = littlefs
upload_speed = 921600
monitor_speed = 115200
; monitor_filters = esp32_exception_decoder
; build_type = debug
build_flags =
  -Wno-deprecated-declarations
	-D CONFIG_ESP32_WIFI_RX_BUFFER_NUM=16
  -D CONFIG_ESP32_WIFI_TX_BUFFER_NUM=16
  -D CONFIG_LWIP_MAX_SOCKETS=16
  -D CONFIG_LWIP_SO_REUSE=1
  -D CONFIG_LWIP_TCP_QUEUE_OOSEQ=0
;  -D DEBUG
;  -D DEBUG_ESPUI
  -D ESPUI_LITTLEFS
;  -D SOLE_OUTPUT
;  -D OLED
	-D FIRMARE_VER=0x0300   ; Firmware given over Artnet (2 bytes)
  -D PIN_DMX_DIR_A=23     ; equals D1mini D7
  -D PIN_DMX_DIR_B=26     ; equals D1mini D0
  -D PIN_PORT_A_TX=17     ; equals D1mini D3
  -D PIN_PORT_B_TX=16     ; equals D1mini D4
  -D PIN_PORT_A_RX=22     ; equals D1mini D1
  -D PIN_PORT_B_RX=-1     ; just a dummy
  -D PIN_STATUS_LED=19    ; equals D1mini D6
  -D PIN_RESET_CONFIG=18  ; equals D1mini D5
  -D PIN_OLED_SDA=21      ; equals D1mini D2
  -D PIN_OLED_SCL=5       ; equals D1mini D8

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
  someweisguy/esp_dmx ;Manually fix line 32 in /src/dmx/hal/uart.c to #if SOC_UART_NUM > 2
  bblanchon/ArduinoJson@^6.21.5
  makuna/NeoPixelBus
  s00500/ESPUI
  adafruit/Adafruit SSD1306
board_build.filesystem = littlefs
upload_speed = 921600
monitor_speed = 115200
; monitor_filters = esp32_exception_decoder
; build_type = debug
build_flags =
  -Wno-deprecated-declarations
  -D CONFIG_LWIP_MAX_SOCKETS=16
  -D CONFIG_LWIP_SO_REUSE=1
  -D CONFIG_LWIP_TCP_QUEUE_OOSEQ=0
  -DCORE_DEBUG_LEVEL=5
;  -D DEBUG
;  -D DEBUG_ESPUI
  -D ESPUI_LITTLEFS
;  -D SOLE_OUTPUT
;  -D OLED
	-D FIRMARE_VER=0x0300   ; Firmware given over Artnet (2 bytes)
  -D PIN_DMX_DIR_A=5
  -D PIN_DMX_DIR_B=6
  -D PIN_PORT_A_TX=9
  -D PIN_PORT_B_TX=8
  -D PIN_PORT_A_RX=10
  -D PIN_PORT_B_RX=-1     ; just a dummy
  -D PIN_STATUS_LED=48
  -D PIN_RESET_CONFIG=47

[env:lolin_s3_mini]
platform = espressif32
board = lolin_s3_mini
framework = arduino
lib_deps =
  someweisguy/esp_dmx ;Manually fix line 32 in /src/dmx/hal/uart.c to #if SOC_UART_NUM > 2
  bblanchon/ArduinoJson@^6.21.5
  makuna/NeoPixelBus
  s00500/ESPUI
  adafruit/Adafruit SSD1306
board_build.filesystem = littlefs
upload_speed = 921600
monitor_speed = 115200
; monitor_filters = esp32_exception_decoder
; build_type = debug
build_flags =
  -Wno-deprecated-declarations
  -D CONFIG_LWIP_MAX_SOCKETS=16
  -D CONFIG_LWIP_SO_REUSE=1
  -D CONFIG_LWIP_TCP_QUEUE_OOSEQ=0
;  -DCORE_DEBUG_LEVEL=5
;  -D DEBUG
;  -D DEBUG_ESPUI
  -D ESPUI_LITTLEFS
;  -D SOLE_OUTPUT
;  -D OLED
	-D FIRMARE_VER=0x0300   ; Firmware given over Artnet (2 bytes)
  -D PIN_DMX_DIR_A=11     ; equals D1mini D7
  -D PIN_DMX_DIR_B=4      ; equals D1mini D0
  -D PIN_PORT_A_TX=43     ; equals D1mini TX
  -D PIN_PORT_B_TX=16     ; equals D1mini D4
  -D PIN_PORT_A_RX=44     ; equals D1mini RX
  -D PIN_PORT_B_RX=-1     ; just a dummy
  -D PIN_STATUS_LED=13    ; equals D1mini D6
  -D PIN_RESET_CONFIG=12  ; equals D1mini D5
  -D PIN_OLED_SDA=35      ; equals D1mini D2
  -D PIN_OLED_SCL=36      ; equals D1mini D1
